project:
  type: website
  output-dir: docs
  resources: images

website:
  title: "Operation Galiwatch"
  favicon: "images/teaswamp_transparent.png"
  page-footer:
    center: |
      *a Tea Swamp project* 
      <br>
      <img src="https://raw.githubusercontent.com/teaswamp-creations/galiwatch.ca/quarto-website/images/teaswamp_transparent.png" alt="logo" class="image" style="width: 2.5em;">
  google-analytics: "G-YZBNVRR4EQ"
  navbar:
    left: 
      - text: Project Details
        href: project.qmd
      - pollinators.qmd
    right:
      - text: Research blog
        href: blog.qmd
      - about.qmd
      - text: Contact
        href: contact.qmd
      - icon: github
        href: https://github.com/teaswamp-creations
  search: 
    location: navbar
    type: overlay
  
format:
  html:
    theme: 
      light: [yeti, css/light-theme.scss]
      dark: [yeti, css/dark-theme.scss]
    include-in_header: favicon.html
    include-after_body: footer.html
    css: ["https://use.fontawesome.com/releases/v6.0.0/css/all.css"]



